### ISSUE TITLE
Can't find check.ipynb for view transformation

### ISSUE THREAD

**Issue by drilistbox** [Sense-GVT/Fast-BEV#10]
Hi, I can't find check.ipynb for view transformation.
![img_v2_c14feb41-ddba-4c8b-9a3b-fdbe3a7dedbg](https://user-images.githubusercontent.com/14495189/217982497-359009f7-2df8-4a79-b952-b9df0666c7aa.jpg)

**Comment by ymlab** [comment]
Updated here: 
https://github.com/Sense-GVT/Fast-BEV/blob/dev/script/view_tranform_cuda/check.ipynb
