### ISSUE TITLE
how to use view_transform cuda module?

### ISSUE THREAD

**Issue by Capchenxi** [Sense-GVT/Fast-BEV#11]
Hi, 

The work from Fast-BEV is great! I have few questions of the recent updates in the repo:

1) How to use the view_transform_cuda when transferring from .pth into trt model?
2) Is there any reason that you split export_2d and export_3d?

I guess I suppose to combine the expoert_2d_onnx, export_3d_onnx with the view_transform_cuda together to generate the trt model so that the acceleration of the model could be realized. But I'm not sure if it is correct.

**Comment by ymlab** [comment]
During deployment, the model is divided into 2D part and 3D part and deployed separately, and the intermediate 2D to 3D part and post-processing part need to be implemented in the SDK.
