### ISSUE TITLE
在当前释放的repo中，没有发现时序对齐的部分，能提供以下Code链接么？

### ISSUE THREAD

**Issue by matrix97317** [Sense-GVT/Fast-BEV#12]

**Comment by ymlab** [comment]
相邻帧图片到当前帧bev通过构造lidaradj2lidarcurr在数据处理阶段对齐，后续数据处理和2d模型阶段按同样的方式处理这些多帧输入，多帧融合阶段就是按照多帧6v的方式分别完成bev投影+cat融合，一些参考链接：
https://github.com/Sense-GVT/Fast-BEV/blob/dev/mmdet3d/datasets/nuscenes_dataset.py#L369
https://github.com/Sense-GVT/Fast-BEV/blob/dev/mmdet3d/datasets/pipelines/transforms_3d.py#L1836
https://github.com/Sense-GVT/Fast-BEV/blob/dev/mmdet3d/models/detectors/fastbev.py#L187

**Comment by matrix97317** [comment]
也就是说，构造t帧的内外参，t-1 的内外参数+到t帧的transform（刚体变换），在2D to 3D阶段，t帧可以取到t的图像数据+t-1的图像数据？

**Comment by ymlab** [comment]
> 也就是说，构造t帧的内外参，t-1 的内外参数+到t帧的transform（刚体变换），在2D to 3D阶段，t帧可以取到t的图像数据+t-1的图像数据？

是这个思路，拿到t-1帧的图像对应当前bev的变换关系之后，就直接把t-1帧数据按照当前帧的方式使用就好了，只不过两帧特征融合的方式还是分别先拿到bev特征再cat融合。
