### ISSUE TITLE
from petrel_client import client

### ISSUE THREAD

**Issue by Rex-LK** [Sense-GVT/Fast-BEV#14]
how to install petrel_client?pip cannot install it

**Comment by ymlab** [comment]
Petrel backend is not always necessary, refer to this link: 
https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py#L30

**Comment by Rex-LK** [comment]
> Petrel backend is not always necessary, refer to this link: https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py#L30
ok !thank you
