### ISSUE TITLE
请问一下,如何在 xaiver 或和 orin 中部署呢?

### ISSUE THREAD

**Issue by lucianzhong** [Sense-GVT/Fast-BEV#16]
请问一下,如何在 xaiver 或和 orin 中部署呢?

**Comment by ymlab** [comment]
模型部分需要拆分成2d部分和3d部分，中间2d转3d和后处理需要在sdk里集成，其中2d/3d部分先转onnx格式再部署到对应平台就可以了，印象中fastbev模型部署到xavier和orin这两个平台不涉及不支持算子的问题。模型部分的onnx部署在整理中，计划后续放出。

**Comment by lucianzhong** [comment]
谢谢回复,期待更新

**Comment by cyn-liu** [comment]
@ymlab  您好：
请问模型部分的onnx部署代码整理好了吗？期待分享！

**Comment by cyn-liu** [comment]
@lucianzhong 你好，请问你完成部署了吗，请问如何使用tensorrt加速这个模型？
