### ISSUE TITLE
请问训练的话需要完整的数据集还是mini数据集就行？

### ISSUE THREAD

**Issue by Rex-LK** [Sense-GVT/Fast-BEV#19]

**Comment by Rex-LK** [comment]
因为我这边使用mini数据集进行训练和测试会报错

**Comment by ymlab** [comment]
是完整数据集，mini集可能要试试对应改一些地方，不过我没尝试过。

**Comment by Rex-LK** [comment]
感谢，如果要用mini数据集应该是要重新生成 ， 应该是需要重新生成nuscenes_infos_test_4d_interval3_max60.pkl nuscenes_infos_train_4d_interval3_max60.pkl
 nuscenes_infos_val_4d_interval3_max60.pkl 这几个文件，请问您是用哪个脚本生成这几个文件的呢？

**Comment by ymlab** [comment]
可以参考这个，是沿用bevdet4d的处理格式。
https://github.com/Sense-GVT/Fast-BEV/blob/dev/tools/data_converter/nuscenes_seq_converter.py

**Comment by ymlab** [comment]
> 感谢，如果要用mini数据集应该是要重新生成 ， 应该是需要重新生成nuscenes_infos_test_4d_interval3_max60.pkl nuscenes_infos_train_4d_interval3_max60.pkl nuscenes_infos_val_4d_interval3_max60.pkl 这几个文件，请问您是用哪个脚本生成这几个文件的呢？

可以参考这个，是沿用bevdet4d的处理方式：https://github.com/Sense-GVT/Fast-BEV/blob/dev/tools/data_converter/nuscenes_seq_converter.py

**Comment by zouzouwei** [comment]
#23 you can see it

**Comment by Rex-LK** [comment]
> 感谢！
