### ISSUE TITLE
mAP and NDS Gap

### ISSUE THREAD

**Issue by guoqi-code** [Sense-GVT/Fast-BEV#20]
For this config "fastbev_m0_r18_s256x704_v200x200x4_c192_d2_f4.py",  I can get the eval result(mAP: 0.2730, NDS: 0.3954) at epoch20, but in your paper, result of experiment M0, mAP:0.284, NDS:0.427, So what will cuase the gap?

**Comment by ymlab** [comment]
Our training accuracy under this setting is mAP0.277&NDS0.411. For reference, here are some checkpoints and evaluation logs: https://drive.google.com/drive/folders/1Ja9mqOE0iGPysVxmLSrZyUoCEBYu5fMH?usp=sharing

**Comment by LaCandela** [comment]
I am having the same problem, I can only get NDS=0.2 after training, just about half as much as the pretrained model produces.
