### ISSUE TITLE
pretrained_models/cascade_mask_rcnn_r18_fpn_coco-mstrain_3x_20e_nuim_bbox_mAP_0.5110_segm_mAP_0.4070.pth is not found! 

### ISSUE THREAD

**Issue by drilistbox** [Sense-GVT/Fast-BEV#5]
Will you provide the pretrained-pth file

**Comment by ymlab** [comment]
The download address of the r18 pre-trained model has been updated in the readme.

**Comment by Ignite616** [comment]
> The download address of the r18 pre-trained model has been updated in the readme.

sorry,I haven't find the r18 pre-trained model in the readme.

**Comment by ymlab** [comment]
> > The download address of the r18 pre-trained model has been updated in the readme.
> 
> sorry,I haven't find the r18 pre-trained model in the readme.

https://drive.google.com/drive/folders/19BD4totDHtwnHtOqTdn0xYJh7stwYd9l

**Comment by Ignite616** [comment]
I want to use Resnet101 as backbone, input image resolution is set to 900x1600. Where can I find the corresponding pretrained model pretrained_models/cascade_mask_rcnn_r101_fpn_coco-mstrain_3x_20e_nuim_bbox.pth?
