### ISSUE TITLE
请问Dataset preparation中的 v1.0-test 和 v1.0-trainval 在哪，网盘里面好像没有这两个文件夹

### ISSUE THREAD

**Issue by 15116513319** [Sense-GVT/Fast-BEV#52]

**Comment by 15116513319** [comment]
我在运行tools/test.py文件时报错说需要这两个文件夹，但是在网盘里没有找到，希望各位大佬谁之前已经下载了能分享一下，万分感谢！！！

**Comment by usugami** [comment]
可以去nuscenes官网上（www.nuscenes.org）的Download下载这两个文件，Full Dataset下面有Trainval和Test两个小类，下载里面的Metadata就行
