### ISSUE TITLE
关于映射表LUT

### ISSUE THREAD

**Issue by fengguibinyn** [Sense-GVT/Fast-BEV#53]
对单帧推理而言，LUT是静态的，在多帧推理过程中除了当前帧，对于历史帧而言，LUT是否也为静态，按照代码而言，他是动态的，每帧构件LUT需要10ms以上的时间，对多帧推理会有很高的延迟

**Comment by fengguibinyn** [comment]
是否有更快的对齐方法

**Comment by 51762344** [comment]
怎么感觉这个映射表和SimpleBEV，M2bev没啥区别

**Comment by loserhou** [comment]
> 怎么感觉这个映射表和SimpleBEV，M2bev没啥区别

我也觉得，纯纯诈骗
