### ISSUE TITLE
作者在orin nx上部署时选择的pytorch版本是多少？

### ISSUE THREAD

**Issue by 15116513319** [Sense-GVT/Fast-BEV#54]
我的环境安装好后出现了这个问题：AttributeError: module "torch.distributed' has no attribute "ReduceOp“，请问该如何解决呢？

**Comment by 15116513319** [comment]
已解决

**Comment by Guts-42** [comment]
> 已解决

请问你是如何解决这个问题的，我在jetson xavier nx上也遇到了同样的问题。万分感谢

**Comment by 15116513319** [comment]
可能是安装的pytorch版本太高了，我之前安装的1.14和2.0版本的pytorch都出现了这个问题，换成1.12版本的就，没问题了

**Comment by Guts-42** [comment]
> 可能是安装的pytorch版本太高了，我之前安装的1.14和2.0版本的pytorch都出现了这个问题，换成1.12版本的就，没问题了

感谢！
