### ISSUE TITLE
重新训练网络，AP始终为0，无法复现论文精度

### ISSUE THREAD

**Issue by Mandylove1993** [Sense-GVT/Fast-BEV#60]
你好，我在云平台训练了20个epoch的不加时序的模型，但是AP始终为0, 代码结构丝毫未变，可以请教一下什么样的配置可以复现论文的结果？

**Comment by Mandylove1993** [comment]
优化器的问题，，但是训练还是不稳定，需要resume才行

**Comment by LiuXuan66** [comment]
> 优化器的问题，，但是训练还是不稳定，需要resume才行

请问能详细说明优化器的具体问题以及如何纠正它们吗

**Comment by cmj18** [comment]
请教下，resume之后就能复现精度么
