### ISSUE TITLE
Can the head be replaced by Centerhead

### ISSUE THREAD

**Issue by 51762344** [Sense-GVT/Fast-BEV#67]

**Comment by 51762344** [comment]
I adjusted the coordinates to make the module adapt to the centerpoint head, but it behaves very poorly. Does anyone have any ideas?

**Comment by 51762344** [comment]
I simply combine the ViewTransformer module & the Centerpoint head and just got about 15%map on nuscenes

**Comment by Byte247** [comment]
Hi, I am trying to do the same but my HM loss does not seem to decrease. How did you do it on your side?
